# Generated by Django 5.2.7 on 2026-03-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_author_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
